# Generated by Django 3.1.2 on 2020-12-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_contactos_name_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactos',
            options={'ordering': ['first_name']},
        ),
    ]
