# Generated by Django 3.1.2 on 2020-12-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_auto_20201219_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactos',
            options={'ordering': ['name_user']},
        ),
        migrations.AlterField(
            model_name='contactos',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
